---
- name: Enforce s3 bucket versioning on AWS account
  hosts: localhost
  gather_facts: false

  tasks:
    - name: List S3 buckets in AWS account
      amazon.aws.s3_bucket_info:
      register: result
    
    - debug:
        var: result
    
    - name: Enable versioning on S3 bucket
      amazon.aws.s3_bucket:
        name: "{{ item.name }}"
        versioning: yes
      loop: "{{ result.buckets }}" 

    - name: Delete all S3 buckets
      amazon.aws.s3_bucket:
        name: "{{ item.name }}"
        state: absent
      loop: "{{ result.buckets }}"
